### ISSUE TITLE
Add option to  choose preferred package manager (Yarn or npm)

### ISSUE THREAD

**Issue by tinesoft** [technote-space/release-github-actions#205]
## Please describe your suggestion: 提案の概要

`npm` default package manager has become as fast and reliable as `Yarn` over the last updates (maybe even more)

## Describe the solution you'd like: 考えうる解決方法

Add a option to allow choosing which package manager to use to install deps:
- name: PACKAGE_MANAGER
- description: Package manager
- default: 'yarn'

## Additional context: 補足

Currently, people using this action with `npm` as package manager, get this warning:

```
##[warning]  >> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

I can provide a PR with thoses changes if approved

**Comment by technote-space** [comment]
@tinesoft 
Thank you for your issue.
I completely forgot about `npm`.

> I can provide a PR with thoses changes if approved

Pull requests to resolve this issue are welcome!
(There is no problem if there is no test.)

**Comment by tinesoft** [comment]
Konichiwa!

Alright, i will start crafting that PR then ;-)
And just like you, I consider tests as important as code, so I'll add them along.

By the way, great work you've done here 👍.
