### ISSUE TITLE
(docs): Mention that 'CLEAN_TARGETS' is part of the default 'BUILD_COMMAND'

### ISSUE THREAD

**Issue by s-weigand** [technote-space/release-github-actions#237]
First of all thanks for that great action, this is eactly what I was looking for 😃.

## Please describe your suggestion: 
Took me some time to figure out why `CLEAN_TARGETS`, didn't work as I intended.
After I had a peak at the source code, i found that it was part of the default build command and I changed my `package.json` to use `build` as task name and unset `BUILD_COMMAND`.

## Describe the solution you'd like: 
So it would be nice for future users to add a line in the description of `CLEAN_TARGETS` like:

Ignored if `BUILD_COMMAND` is provided.

## Describe alternatives you've considered: 
Another option would be to make `CLEAN_TARGETS` independent from `BUILD_COMMAND` (which was my first naive guess how it is supposed to work).

**Comment by technote-space** [comment]
@s-weigand 
I understand and agree with your suggestion. 
I'll update README soon.
And I'll divide the commands into build and clear files phase, 
the build phase uses `BUILD_COMMAND` and the clear files phase uses `CLEAN_TARGETS`.
This is breaking change so that I will release this as v2.
