### ISSUE TITLE
Use npm `prepare` script as the build command

### ISSUE THREAD

**Issue by jasonkarns** [technote-space/release-github-actions#348]
## Please describe your suggestion: 提案の概要
I'm rather confused why the default build command doesn't include the hook that npm itself documents as the appropriate way to build an npm package: `prepare`.

The prepare hook is run automatically for pack and publish events, _and also_ for bare npm-installs (which is necessary to support building of packages that are required as git-dependencies).

This hook is designed specifically to be the script invoked for package compilation (babel, typescript, bundling, browserify, etc)

## Describe the solution you'd like: 考えうる解決方法

As npm considers `prepare` to be the recommended build script, I would expect `prepare` to:
a) be included in the `BUILD_COMMAND` option default list
b) be _preferred_ among all other build commands if multiple are present

## Additional context: 補足
[Documentation from npm](https://docs.npmjs.com/misc/scripts#prepublish-and-prepare) around the history, rationale, and use case for `prepare` script.

**Comment by technote-space** [comment]
I will add `prepare` to `BUILD_COMMAND`.
