### ISSUE TITLE
Permit skipping or fully customizing installation step

### ISSUE THREAD

**Issue by kadamwhite** [technote-space/release-github-actions#441]
## Please describe your suggestion: 提案の概要

If you are using a recent version of Node, and your peer dependencies include conflicts, it is possible to install successfully locally (or in a separate GitHub action) using the `--legacy-peer-deps` flag. However, I have been unable to successfully configure this action to work properly, because there is no clear way to modify the installation command. And then, after the build, `npm install --production` is still automatically run by this action in many cases, which also fails.

## Describe the solution you'd like: 考えうる解決方法

I would like it to be possible for us to specify our own full build commands, for example so we can run `npm ci --legacy-peer-deps`, and not have the action try to inject any install command for us, before or after the build.

There is documentation about customizing the install command, but the logic I see,
```
const hasInstallCommand       = !!commands.filter(command => command.includes(`${runCommand}install`)).length;
```
seems to expect that we have created our own `npm run install` script, which is not valid. If you put your own script with the alias "install," `npm` may sometimes loop infinitely.

## Describe alternatives you've considered: 考えうる代替案

Either an INSTALL_COMMAND option, which if present will deactivate all pre- and post-build installation command injection, or perhaps a SKIP_INSTALL flag which would require us to have run the appropriate package manager install previously.

## Additional context: 補足

[This failed action run](https://github.com/humanmade/hm-post-history/actions/runs/3153703585/jobs/5130475554) from one of our packages demonstrates how peer dependency resolution can block a build.

**Comment by technote-space** [comment]
This action is for the release of GitHub Actions
